const products = [
  {
    _id: '1',
    name: 'Coffa',
    image: '/image/coffa.jpg',
    description: 'Coffa guebsia 100% s3af tounsi',
    Category: 'decoration',
    price: '30',
    rating: '3',
    CountInStock: '3',
    adressProduct: 'Tunis',
    numberReviews: '8',
  },
  {
    _id: '2',
    name: 'Serum',
    image: '/image/serum.jpg',
    description: 'serum cheveux 100% naturel',
    Category: 'Produit bio',
    price: '20',
    rating: '4.5',
    CountInStock: '2',
    adressProduct: 'Mestir',
    numberReviews: '5',
  },
  {
    _id: '3',
    name: 'bonnet',
    image: '/image/bonet.jpg',
    description: 'bonet crochet made with love',
    Category: 'Vétement',
    price: '12',
    rating: '4',
    CountInStock: '1',
    adressProduct: 'Sfax',
    numberReviews: '4',
  },
  {
    _id: '4',
    name: 'bonnet',
    image: '/image/bonet.jpg',
    description: 'bonet crochet made with love',
    Category: 'Vétement',
    price: '12',
    rating: '4',
    CountInStock: '0',
    adressProduct: 'Hammamet',
    numberReviews: '4',
  },
  {
    _id: '5',
    name: 'bonnet',
    image: '/image/bonet.jpg',
    description: 'bonet crochet made with love',
    Category: 'Vétement',
    price: '12',
    rating: '4',
    CountInStock: '1',
    adressProduct: 'Tunis',
    numberReviews: '4',
  },
  {
    _id: '6',
    name: 'bonnet',
    image: '/image/bonet.jpg',
    description: 'bonet crochet made with love',
    Category: 'Vétement',
    price: '12',
    rating: '4',
    CountInStock: '1',
    adressProduct: 'Tunis, Marsa',
    numberReviews: '4',
  },
]

export default products
